import Link from "next/link"
import "./styles.css";
import Footer from "./components/footer";

export const metadata = {
  title: {
    default: "ABC Constructions",
    template: " %s | ABC Constructions"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="relative bg-cover bg-center p-6 shadow-md" style={{ backgroundColor: "#404040" }}>
          <div className="container mx-auto flex flex-col items-center md:flex-row md:items-start">
            <div className="flex items-center w-full md:w-auto">
              <img src="/abc-logo.jpg" alt="Company Logo" className="h-12 w-12 mr-4" /> {/* Adjust the logo size as needed */}
              <div>
                <h1 className="text-4xl font-bold text-white">ABC Constructions</h1>
                <p className="text-white mt-2">Building your dreams into reality</p> {/* Example quote */}
              </div>
            </div>
            <nav className="mt-4 md:mt-0 md:ml-auto flex space-x-4">
              <Link href="#about"
                className="text-white hover:bg-light-grey transition-colors duration-300 p-2 rounded">About
              </Link>
              <Link href="#services"
                className="text-white hover:bg-light-grey transition-colors duration-300 p-2 rounded">Services
              </Link>
              <Link href="#projects"
                className="text-white hover:bg-light-grey transition-colors duration-300 p-2 rounded">Projects
              </Link>
              <Link href="#prefooter"
                className="text-white hover:bg-light-grey transition-colors duration-300 p-2 rounded">Contact
              </Link>
            </nav>
          </div>
        </header>

        <div>
          {children}
        </div>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
